geoip_location = "GeoIP2-Country.mmdb"
interface_name = "en0"

log_file = "logs/swiftlink.log"
log_level = "debug"
log_max_file_size = "10mb"
log_files = 3

[dns]
binds = ["0.0.0.0:1053 -udp", "0.0.0.0:1053 -tcp"]
servers = ["223.5.5.5", "8.8.8.8"]
edns_client_subnet = "192.168.1.1/24"
use_hosts_file = true
fake_ip = true
fake_ip_range = "198.18.0.0/15"
fake_ip6_range = "fc00::/18"
fake_ip_filter = ["zenlayer.com", ".zenlayer.com"]
[dns.proxy_servers]
mysocks5proxy = "socks5://user:pass@1.2.3.4:1080"
myhttpproxy = "http://user:pass@1.2.3.4:3128"
